In [93]:
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [94]:
##Final data with team network stats
#df = pd.read_csv('./data/final_networked_by_team.csv')
df = pd.read_csv('./data/final_networked.csv')

In [95]:
df[['Pos', 'College','team','Draft_Team']] = df[['Pos', 'College','team','Draft_Team']].fillna(value="")
df[['Draft_Round', 'Draft_Pick','Draft_Year','crimeCount','No','GS']] = df[['Draft_Round', 'Draft_Pick','Draft_Year','crimeCount','No','GS']].fillna(value=0)

avgAge = math.floor(df['Age'].mean())
avgHt = math.floor(df['Ht'].mean())
avgWt = math.floor(df['Wt'].mean())
avgBD = math.floor(df['BirthDate'].mean())
df['Age'] = df['Age'].fillna(value=avgAge)
df['Ht'] = df['Ht'].fillna(value=avgHt)
df['Wt'] = df['Wt'].fillna(value=avgWt)
df['BirthDate'] = df['BirthDate'].fillna(value=avgBD)

In [96]:
#df.head()
df[['Pos', 'College','team','Draft_Team']].sample();
list(df)
df[['Age','Wt','Ht','G','GS', 'BirthDate','Yrs','year','Draft_Round','Draft_Pick','Draft_Year','crimeCount','player_Degrees','player_Eigen','player_BiDegree','Team_Degrees','Team_Closeness','Team_Betweenness']].describe()

Age            Wt            Ht             G            GS  \
count  33282.000000  33282.000000  33282.000000  33282.000000  33282.000000   
mean      26.646806    243.628268     74.004507     11.523286      5.751337   
std        3.399155     45.076659      0.392354      5.163789      6.310930   
min       20.000000    150.000000     66.000000      1.000000      0.000000   
25%       24.000000    205.000000     74.000000      7.000000      0.000000   
50%       26.000000    236.000000     74.000000     14.000000      3.000000   
75%       29.000000    281.000000     74.000000     16.000000     12.000000   
max       47.000000    376.000000     80.000000     16.000000     16.000000   

           BirthDate           Yrs          year   Draft_Round    Draft_Pick  \
count   33282.000000  33282.000000  33282.000000  33282.000000  33282.000000   
mean   724114.593474      3.551499   2008.205186      2.560423     74.454901   
std      4296.345344      3.302294      4.879879      2.371071     91.756132   
min    718800.000000     -3.000000   2000.000000      0.000000      0.000000   
25%    722042.000000      1.000000   2004.000000      0.000000      0.000000   
50%    723690.000000      3.000000   2008.000000      2.000000     49.000000   
75%    725446.000000      5.000000   2012.000000      4.000000    128.000000   
max    755320.000000     25.000000   2016.000000     12.000000   2010.000000   

         Draft_Year    crimeCount  player_Degrees  player_Eigen  \
count  33282.000000  33282.000000    33282.000000  33282.000000   
mean    1430.347665      0.021814      983.535845      0.012325   
std      905.981534      0.157174      506.680106      0.006349   
min        0.000000      0.000000      327.000000      0.003090   
25%        0.000000      0.000000      482.000000      0.006350   
50%     2001.000000      0.000000      883.000000      0.011299   
75%     2007.000000      0.000000     1290.000000      0.016396   
max     2016.000000      4.000000     3528.000000      0.040973   

       player_BiDegree  Team_Degrees  Team_Closeness  Team_Betweenness  
count     33282.000000  33282.000000    33282.000000      33282.000000  
mean         70.252560     36.281233        0.364585          0.055353  
std          36.191436      7.881125        0.009935          0.016987  
min          23.357143     21.000000        0.341232          0.022637  
25%          34.428571     31.000000        0.358655          0.042566  
50%          63.071429     37.000000        0.365947          0.056650  
75%          92.142857     41.000000        0.370656          0.070111  
max         252.000000     50.000000        0.382979          0.085786

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33282 entries, 0 to 33281
Data columns (total 39 columns):
No                       33282 non-null float64
name                     33282 non-null object
Age                      33282 non-null float64
Pos                      33282 non-null object
G                        33282 non-null float64
GS                       33282 non-null float64
Wt                       33282 non-null float64
Ht                       33282 non-null float64
College                  33282 non-null object
BirthDate                33282 non-null float64
Yrs                      33282 non-null int64
AV                       33281 non-null float64
team                     33282 non-null object
year                     33282 non-null float64
Draft_Team               33282 non-null object
Draft_Round              33282 non-null float64
Draft_Pick               33282 non-null float64
Draft_Year               33282 non-null float64
crimeCount               33282 non

In [98]:
df.describe()

No           Age             G            GS            Wt  \
count  33282.000000  33282.000000  33282.000000  33282.000000  33282.000000   
mean      53.091401     26.646806     11.523286      5.751337    243.628268   
std       28.872952      3.399155      5.163789      6.310930     45.076659   
min        0.000000     20.000000      1.000000      0.000000    150.000000   
25%       27.000000     24.000000      7.000000      0.000000    205.000000   
50%       54.000000     26.000000     14.000000      3.000000    236.000000   
75%       80.000000     29.000000     16.000000     12.000000    281.000000   
max       99.000000     47.000000     16.000000     16.000000    376.000000   

                 Ht      BirthDate           Yrs            AV          year  \
count  33282.000000   33282.000000  33282.000000  33281.000000  33282.000000   
mean      74.004507  724114.593474      3.551499      3.370121   2008.205186   
std        0.392354    4296.345344      3.302294      3.601035      4.879879   
min       66.000000  718800.000000     -3.000000     -5.000000   2000.000000   
25%       74.000000  722042.000000      1.000000      1.000000   2004.000000   
50%       74.000000  723690.000000      3.000000      2.000000   2008.000000   
75%       74.000000  725446.000000      5.000000      6.000000   2012.000000   
max       80.000000  755320.000000     25.000000     26.000000   2016.000000   

             ...                Sex  Theft / Burglary  Murder / Manslaughter  \
count        ...         679.000000        679.000000             679.000000   
mean         ...           0.026510          0.027982               0.008837   
std          ...           0.160763          0.173751               0.093656   
min          ...           0.000000          0.000000               0.000000   
25%          ...           0.000000          0.000000               0.000000   
50%          ...           0.000000          0.000000               0.000000   
75%          ...           0.000000          0.000000               0.000000   
max          ...           1.000000          2.000000               1.000000   

       Animal Abuse  player_Degrees  player_Eigen  player_BiDegree  \
count    679.000000    33282.000000  33282.000000     33282.000000   
mean       0.008837      983.535845      0.012325        70.252560   
std        0.093656      506.680106      0.006349        36.191436   
min        0.000000      327.000000      0.003090        23.357143   
25%        0.000000      482.000000      0.006350        34.428571   
50%        0.000000      883.000000      0.011299        63.071429   
75%        0.000000     1290.000000      0.016396        92.142857   
max        1.000000     3528.000000      0.040973       252.000000   

       Team_Degrees  Team_Closeness  Team_Betweenness  
count  33282.000000    33282.000000      33282.000000  
mean      36.281233        0.364585          0.055353  
std        7.881125        0.009935          0.016987  
min       21.000000        0.341232          0.022637  
25%       31.000000        0.358655          0.042566  
50%       37.000000        0.365947          0.056650  
75%       41.000000        0.370656          0.070111  
max       50.000000        0.382979          0.085786  

[8 rows x 34 columns]

In [99]:
##Handling categorical data
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

pos = df['Pos']
le.fit(pos)
po = le.transform(pos)
df['Pos'] = po

col = df['College']
le.fit(col)
co = le.transform(col)
df['College'] = co

team = df['team']
le.fit(team)
te = le.transform(team)
df['team'] = te

dteam = df['Draft_Team']
le.fit(dteam)
dte = le.transform(dteam)
df['Draft_Team'] = dte



In [100]:
df.to_csv('data/final_encoded.csv')

In [101]:
dropList = ['No','name','crimeCount','DUI','Other','Drugs','Domestic Violence','Resisting','Assault / Battery','Gun','Alcohol','License / Traffic','Disorderly conduct','Sex','Theft / Burglary','Murder / Manslaughter','Animal Abuse','AV']

#X = df.drop(dropList, axis=1)
#X = df[['player_Degrees', 'player_Eigen', 'player_BiDegree','Team_Degrees', 'Team_Closeness','Team_Betweenness']]
X = df[['player_BiDegree','Team_Degrees', 'Team_Closeness','Team_Betweenness']]
y = df['crimeCount']

X.isnull().any()




player_BiDegree     False
Team_Degrees        False
Team_Closeness      False
Team_Betweenness    False
dtype: bool

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 22)

In [103]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 300)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [104]:
rfc_pred = rfc.predict(X_test)


In [105]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, rfc_pred))

             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99     13050
        1.0       0.17      0.05      0.08       249
        2.0       0.00      0.00      0.00        14

avg / total       0.97      0.98      0.97     13313



In [106]:
print(confusion_matrix(y_test, rfc_pred))

[[12990    59     1]
 [  234    13     2]
 [   11     3     0]]


In [107]:
from sklearn.naive_bayes import GaussianNB
skgnb = GaussianNB()
skgnb.fit(X_train,y_train)
train_predict = skgnb.predict(X_train)
#print(train_predict)

#see how accurate the training data was fit
from sklearn import metrics
print("Training accuracy:",metrics.accuracy_score(y_train, train_predict))

#use the trained model to predict the test values
test_predict = skgnb.predict(X_test)
print("Testing accuracy:",metrics.accuracy_score(y_test, test_predict))

Training accuracy: 0.963192949071
Testing accuracy: 0.966123338091


In [108]:
print("\nClassification Report:")
print(metrics.classification_report(y_test, test_predict, target_names=['NoCrime','Crime','idk']))
print("\nConfusion Matrix:")
skcm = metrics.confusion_matrix(y_test,test_predict)
#putting it into a dataframe so it prints the labels
#skcm = pd.DataFrame(skcm, columns=['predicted-edible','predicted-poisonous'])
#skcm['actual'] = ['edible','poisonous']
#skcm = skcm.set_index('actual')


print(skcm)

print("\nScore (same thing as test accuracy?): ", skgnb.score(X_test,y_test))


Classification Report:
             precision    recall  f1-score   support

    NoCrime       0.98      0.99      0.98     13050
      Crime       0.00      0.00      0.00       249
        idk       0.00      0.00      0.00        14

avg / total       0.96      0.97      0.96     13313


Confusion Matrix:
[[12862     0     0   188]
 [  242     0     0     7]
 [   14     0     0     0]
 [    0     0     0     0]]

Score (same thing as test accuracy?):  0.966123338091


/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1428: UserWarning: labels size, 4, does not match size of target_names, 3
  .format(len(labels), len(target_names))
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
